version: "3.9"

services:
  database:
    image: postgres
    container_name: database_estock
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dbstock
      - POSTGRES_DB=easystock
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: estock
    restart: always
    ports: 
      - 3334:3334
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local